# Generated by Django 2.2.19 on 2021-05-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('repeatability', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('report', 'report'), ('payment', 'payment')], max_length=7)),
                ('regulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tax_calendar.Regulator')),
            ],
        ),
    ]
